#!/bin/bash

user=$(whoami) # User that's installing said extension
argos="/home/$user/.config/argos" # Argos Plugin folder

function zenityc () { # Prevents script from dying if zenity isn't present
    if [ "$(command -v zenity)" ]; then
        zenity "$@"
    else
        return 0
    fi
}

if [[ "$1" == "bitbar:"* || "$1" == "argos:"* ]]; then
    title=${1#*title=}
    title=${title%%&*}
    title=$(python -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))" "$title") # Decode Title

    ref=${1#*src=}
    ref=$(python -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))" "$ref") # Decode Url
    
    script=${ref##*/}

    if echo "$title" | grep "src="; then # Ensure an ordinary title
        title=$script
    elif [ ! "$title" ]; then
        title=$script
    fi

    if ! zenityc --question --title="Argos Plugin Installer" --text="<big>Add plugin <b>$title</b>?</big>\n\n<b><u>Make sure its source is trusted\!</u></b>\n<small><b>Source: <tt>$ref</tt></b></small>" --ellipsize; then
        zenityc --error --text="Installation cancelled" --ellipsize # Cancel if the User decides not to install
        exit 1
    fi

    if [[ ! -d "$argos" ]]; then
        echo "Creating Argos script folder $argos"
        mkdir "$argos" # Add the argos folder if it doesn't exist
    fi

    wget "$ref" -O "$argos/$script" # Download Script
    chmod 755 "$argos/$script"
    
    zenityc --info --title="Argos Plugin Installer" --text="Installed <b>$script</b> succesfully!" --ellipsize

else
    xdg-open "$1" # Just open with the default handler
fi